// Player events
const THROW_CARD_ON_FIELD = 'THROW_CARD_ON_FIELD';
const FINISH_MOVE = 'FINISH_MOVE';
const CARD_BEATED = 'CARD_BEATED';

module.exports = {
  THROW_CARD_ON_FIELD,
  FINISH_MOVE,
  CARD_BEATED
};